from src.database import Base
from src.entities.cargo import Cargo
from src.entities.categoria import Categoria
from src.entities.cliente import Cliente
from src.entities.detalle_venta import DetalleVenta
from src.entities.Empleado import Empleado
from src.entities.garantias import Garantia
from src.entities.inventario import InventarioTienda
from src.entities.juguete import Juguete
from src.entities.promocion import Promocion
from src.entities.Proveedor import Proveedor
from src.entities.Tienda import Tienda
from src.entities.venta import Venta
